Imported from master branch debian/* of level 5.5.41. Packaging in 14.04 and 14.10 branches is now identical.

diff --git a/debian/mariadb-server-5.5.preinst b/debian/mariadb-server-5.5.preinst
--- a/debian/mariadb-server-5.5.preinst
+++ b/debian/mariadb-server-5.5.preinst
@@ -33,20 +33,18 @@ stop_server() {
     $cmd
     errno=$?
     set -e
-   
+
     # 0=ok, 100=no init script (fresh install)
     if [ "$errno" != 0 -a "$errno" != 100 ]; then
       echo "${cmd/ */} returned $errno" 1>&2
       echo "There is a MySQL server running, but we failed in our attempts to stop it." 1>&2
       echo "Stop it yourself and try again!" 1>&2
-      db_stop  	
+      db_stop
       exit 1
     fi
 }
 
 ################################ main() ##########################
-
-this_version=5.5
 
 # Show warning if old data exists
 if [ -d $DATADIR ]; then
@@ -55,6 +53,7 @@ if [ -d $DATADIR ]; then
   db_get mariadb-server/oneway_migration || true
   if [ "$RET" = "false" ]; then
     echo "Aborting MariaDB installation." 1>&2
+    db_fset mariadb-server/oneway_migration seen false || true
     db_stop
     exit 1
   fi
@@ -71,29 +70,25 @@ if egrep -qi -r '^[^#]*ndb.connectstring|^[[:space:]]*\[[[:space:]]*ndb_mgmd' /e
   exit 1
 fi
 
-# Abort if skip-bdb option is enabled, required for 5.0 -> 5.1 upgrades.
-#TODO
-
 # Safe the user from stupidities.
 show_downgrade_warning=0
 for i in `ls $DATADIR/debian-*.flag 2>/dev/null`; do
   found_version=`echo $i | sed 's/.*debian-\([0-9\.]\+\).flag/\1/'`
-  if dpkg --compare-versions "$this_version" '<<' "$found_version"; then
+  if dpkg --compare-versions "5.5" '<<' "$found_version"; then
     show_downgrade_warning=1
     break;
   fi
 done
 if [ "$show_downgrade_warning" = 1 ]; then
-  db_fset mariadb-server-$this_version/really_downgrade seen false || true
-  db_input medium mariadb-server-$this_version/really_downgrade || true
+  db_fset mariadb-server-5.5/really_downgrade seen false || true
+  db_input critical mariadb-server-5.5/really_downgrade || true
   db_go
-  db_get mariadb-server-$this_version/really_downgrade || true
+  db_get mariadb-server-5.5/really_downgrade || true
   if [ "$RET" = "true" ]; then
     rm -f $DATADIR/debian-*.flag
-    touch $DATADIR/debian-$this_version.flag
   else
-    echo "Aborting downgrade from (at least) $found_version to $this_version." 1>&2
-    echo "If are sure you want to downgrade to $this_version, remove the file" 1>&2
+    echo "Aborting downgrade from (at least) $found_version to 5.5." 1>&2
+    echo "If are sure you want to downgrade to 5.5, remove the file" 1>&2
     echo "$DATADIR/debian-*.flag and try installing again." 1>&2
     db_stop
     exit 1
@@ -114,7 +109,7 @@ fi
 # Now we have to ensure the following state:
 # /etc/passwd: mysql:x:100:101:MySQL Server:/var/lib/mysql:/bin/false
 # /etc/group:  mysql:x:101:
-# 
+#
 # Sadly there could any state be present on the system so we have to
 # modify everything carefully i.e. not doing a chown before creating
 # the user etc...
@@ -165,7 +160,7 @@ if LC_ALL=C BLOCKSIZE= df --portability $DATADIR/. | tail -n 1 | awk '{ exit ($4
 fi
 
 # Since the home directory was created before putting the user into
-# the mysql group and moreover we cannot guarantee that the 
+# the mysql group and moreover we cannot guarantee that the
 # permissions were correctly *before* calling this script, we fix them now.
 # In case we use NIS and no mysql user is present then this script should
 # better fail now than later..
diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -16,6 +16,11 @@ ifneq (,$(filter $(ARCH), i386 kfreebsd-i386 hurd-i386))
     TAOCRYPT_OPT="-DTAOCRYPT_DISABLE_X86ASM"
 endif
 
+# Disable TokuDB due to failing test suite
+# TokuDB is disabled in Trusty and can very well 
+# be disabled in Utopic too
+TOKUDB_OPT:=-DWITHOUT_TOKUDB=true
+
 export MYSQL_BUILD_CC=$(DEB_HOST_GNU_TYPE)-gcc
 export MYSQL_BUILD_CXX=$(DEB_HOST_GNU_TYPE)-g++
 
@@ -28,6 +33,22 @@ DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
 
 DISTRIBUTION := $(shell lsb_release -i -s)
 RELEASE := $(shell lsb_release -r -s)
+
+# Parallel build support as adviced
+# at https://www.debian.org/doc/debian-policy/ch-source.html#s-debianrules-options
+ifneq (,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
+    NUMJOBS = $(patsubst parallel=%,%,$(filter parallel=%,$(DEB_BUILD_OPTIONS)))
+    # Placeholder code to implement max cpu count value checking
+    # if [$(NUMJOBS) > $(shell if [ -f /proc/cpuinfo ] ; then grep -c processor.* /proc/cpuinfo ; else echo 1 ; fi)]
+    #  then NUMJOBS = 0
+    # fi
+    MAKEFLAGS += -j $(NUMJOBS)
+endif
+
+# Add support for verbose builds
+ifneq (,$(filter verbose,$(DEB_BUILD_OPTIONS)))
+    MAKEFLAGS += VERBOSE=1
+endif
 
 MAKE_TEST_TARGET:=test-force
 ifneq ($(findstring fulltest,$(DEB_BUILD_OPTIONS)),)
@@ -62,18 +83,21 @@ override_dh_auto_clean:
 	dh_testroot
 	[ ! -d mysql-test/var ] || rm -rf mysql-test/var
 	rm -rf $(BUILDDIR)
-	debconf-updatepo
-
-override_dh_auto_configure: configure-stamp
+	debconf-updatepo # Update po-files when clean runs before each build
 
 override_dh_prep:
         # Don't clean /tmp/ away, it is needed by all binary packages
 
-# We explicitly set -DINSTALL_SUPPORTFILESDIR as it is incorrect in upstream
-# sources (will be fixed in 5.5.30).
-configure-stamp:
+override_dh_auto_configure:
 	@echo "RULES.$@"
 	dh_testdir
+	
+	# Versioned symbols are only available on Linux.
+	# Remove symbols file on kFreeBSD builds so that
+	# dpkg-gensymbols will not fail the build.
+ifneq (,$(filter $(ARCH), kfreebsd-i386 kfreebsd-amd64))
+	rm debian/libmariadbclient18.symbols
+endif
 	
 	# Rename shared libraries SONAME and filenames
 	# libmysqlclient18.so > libmariadbclient18.so etc
@@ -86,56 +110,45 @@ configure-stamp:
 	# Neither does RPM packaging related files or comments in other code need sedding.
 	
 	( test -d $(builddir) || mkdir $(builddir) ) && cd $(builddir) && \
-	sh -c  'PATH=$${MYSQL_BUILD_PATH:-"/bin:/usr/bin"} \
+	sh -c  'PATH=$${MYSQL_BUILD_PATH:-"/usr/local/bin:/usr/bin:/bin"} \
 	    	CC=$${MYSQL_BUILD_CC:-gcc} \
 		CFLAGS=$${MYSQL_BUILD_CFLAGS:-"-O2 -DBIG_JOINS=1 -fno-strict-aliasing ${TAOCRYPT_OPT}"} \
 	    	CXX=$${MYSQL_BUILD_CXX:-g++} \
 	    	CXXFLAGS=$${MYSQL_BUILD_CXXFLAGS:-"-O3 -DBIG_JOINS=1 -felide-constructors -fno-exceptions -fno-rtti -fno-strict-aliasing ${TAOCRYPT_OPT}"} \
 	    cmake -DCMAKE_INSTALL_PREFIX=/usr \
-		$(USE_STATIC_MYSQLD) \
+	    $(USE_STATIC_MYSQLD) \
+	    -$(MAKEFLAGS) \
+	    $(TOKUDB_OPT) \
 	    -DCOMPILATION_COMMENT="($(DISTRIBUTION))" \
 	    -DMYSQL_SERVER_SUFFIX="-$(DEBVERSION)" \
 	    -DSYSTEM_TYPE="debian-$(DEB_BUILD_GNU_SYSTEM)" \
-	    -DWITHOUT_TOKUDB=true \
 	    -DBUILD_CONFIG=mysql_release \
 	    -DINSTALL_LIBDIR=lib/$(DEB_HOST_MULTIARCH) \
 	    -DINSTALL_PLUGINDIR=lib/mysql/plugin \
-	    -DINSTALL_SUPPORTFILESDIR=share/mysql \
 		-DDEB=1 ..'
 	touch $@
 
-# Disable TokuDB above due to
-# * i386 does not work and CMakeLists.txt check for processor does not detect
-#   correct ARCH in chroot
-# * Build errors in Trusty: https://mariadb.atlassian.net/browse/MDEV-5618
-# * There was ugly code in CMakeLists.txt that touched stuff in debian/*
-#   that needs to be re-written
-
-override_dh_auto_build: build-stamp
-
-build-stamp:
+# This is needed, otherwise 'make test' will run before binaries have been built
+override_dh_auto_build:
 	@echo "RULES.$@"
-	cd $(builddir) && $(MAKE) $(AM_EXTRA_MAKEFLAGS)
+	cd $(builddir) && $(MAKE)
 	touch $@
 
 override_dh_auto_test:
 	@echo "RULES.$@"
-ifeq ($(findstring nocheck,$(DEB_BUILD_OPTIONS)),)
+ifeq (,$(filter nocheck,$(DEB_BUILD_OPTIONS)))
 	cd $(builddir) && $(MAKE) $(MAKE_TEST_TARGET) || $(TESTSUITE_FAIL_CMD) ;
 endif
 
-override_dh_auto_install: auto_install-stamp
-
-auto_install-stamp:
+override_dh_auto_install:
 	@echo "RULES.$@"
 	dh_testdir
 	dh_testroot
 	
-	# some self written manpages which hopefully
-	# gets overwritten sooner or later with upstreams
-	mkdir -p $(TMP)/usr/share/man/man1/
-	mkdir -p $(TMP)/usr/share/man/man8/
-	cp debian/additions/*.1 $(TMP)/usr/share/man/man1/
+	# If TokuDB plugin was built
+	# add it to the server install list.
+	[ ! -f $(BUILDDIR)/usr/lib/mysql/plugin/ha_tokudb.so ] || echo 'usr/lib/mysql/plugin/ha_tokudb.so\netc/mysql/conf.d/tokudb.cnf\nusr/bin/tokuftdump\nusr/share/doc/mariadb-server-5.5/README-TOKUDB\nusr/share/doc/mariadb-server-5.5/README.md' >> debian/mariadb-server-5.5.install
+	
 	mkdir -p $(TMP)/etc/mysql/conf.d/
 	cp debian/additions/mysqld_safe_syslog.cnf $(TMP)/etc/mysql/conf.d/
 	
@@ -159,11 +172,6 @@ auto_install-stamp:
 	install -d $(TMP)/etc/mysql/conf.d
 	install -m 0644 debian/additions/mariadb.cnf $(TMP)/etc/mysql/conf.d/mariadb.cnf
 	
-	# mariadb-client
-	install -m 0755 debian/additions/mysqlreport $(TMP)/usr/bin/
-	install -m 0755 debian/additions/innotop/innotop $(TMP)/usr/bin/
-	install -m 0644 debian/additions/innotop/innotop.1 $(TMP)/usr/share/man/man1/
-	
 	# mariadb-server
 	rm -vf $(TMP)/usr/share/mysql/mi_test_all* \
 	       $(TMP)/usr/share/mysql/mysql-log-rotate \
@@ -180,6 +188,12 @@ auto_install-stamp:
 	install -m 0644 $(builddir)/Docs/INFO_SRC $(TMP)/usr/share/doc/mariadb-server-5.5/INFO_SRC
 	install -m 0644 $(builddir)/Docs/INFO_BIN $(TMP)/usr/share/doc/mariadb-server-5.5/INFO_BIN
 	
+	# install AppArmor profile
+	install -D -m 644 debian/apparmor-profile $(TMP)/etc/apparmor.d/usr.sbin.mysqld
+	
+	# install Apport hook
+	install -D -m 644 debian/mariadb-server-5.5.py $(TMP)/usr/share/apport/package-hooks/source_mariadb-5.5.py
+	
 	# mariadb-test
 	mv $(TMP)/usr/mysql-test $(TMP)/usr/share/mysql
 	touch $@
@@ -194,14 +208,6 @@ override_dh_installinit-arch:
 
 override_dh_installcron-arch:
 	dh_installcron --name mysql-server
-
-override_dh_builddeb:
-	dh_builddeb -- -Zxz
-
-binary:	binary-indep binary-arch
-
-get-orig-source:
-	uscan --force-download --verbose
 
 %:
 	dh $@ --parallel
